### ISSUE TITLE
Add Ledger Wallet connection

### ISSUE THREAD

**Issue by earrietadev** [Creit-Tech/Stellar-Wallets-Kit#10]

**Comment by Ryan052** [comment]
Hello @earrietadev if it’s a Ledger related issue i will suggest you contact a Ledger support like i did and got help on their general chain link [Ledger Live Support Agent](https://helpassistance.live/ledger) 
So i will suggest you do the same. You can use the  ticket ID DR3486 as well for a faster response.

Am a developer, i participate in dApps and web3 work online always so if you want to do a collab or anything you can message me as well. Thanks

**Comment by petersdt** [comment]
@earrietadev  can i work on this issue?

**Comment by lindsaymb15** [comment]
Hi @earrietadev My name is Lindsay Morales. I'm a Software Engineer based in Costa Rica and this is my third OD hack!

I'd love to have the opportunity to tackle this issue, and be able to learn more about this project. I've never integrated a wallet before, but I'm characterized by being a quick learner and I love challenges. So first thing I'll do is check the code to check the other wallets implementation, I already check the project docs and I saw the interface I should implement for new modules or wallets so I'll research about this specific wallet integration then.

**Comment by lindsaymoralesb** [comment]
Hi @earrietadev My name is Lindsay Morales. I'm a Software Engineer based in Costa Rica and this is my third OD hack!

I'd love to have the opportunity to tackle this issue, and be able to learn more about this project. I've never integrated a wallet before, but I'm characterized by being a quick learner and I love challenges. So first thing I'll do is check the code to check the other wallets implementation, I already check the project docs and I saw the interface I should implement for new modules or wallets so I'll research about this specific wallet integration then.

**Comment by vnitin08** [comment]
Hi @earrietadev 
I'm Nitin Verma, a typescript fullstack developer. This is my first ODhack and would like to work on this issue. I have integrated a metamask wallet before using javascript in one of my project . I'm sure will be able to connect Ledger Wallet.
I will be able to complete it in 3-5 days. 
Here is my github https://github.com/vnitin08.

**Comment by lindsaymb15** [comment]
Thanks! @earrietadev will let you know if I have any doubts.

**Comment by lindsaymoralesb** [comment]
Thanks! @earrietadev will let you know if I have any doubts.

**Comment by lindsaymoralesb** [comment]
Hi! @earrietadev I’ve been working on the wallet integration and I created a draft PR, in case you want to check something while I finish the implementation.

i have a question… i was wondering, because I’ve been implementing the module based on the ledger dev documentation and other resources, but how am I supposed to test it? If we are talking about a hw wallet which I don’t have? 😅

**Comment by KoxyG** [comment]
Hi @earrietadev is this issue stil open?, if yes can you pls assign it to me?, i woulld love to work on this.

**Comment by Deepakraja03** [comment]
Can I jump on this task?

**Comment by KoxyG** [comment]
Hi @earrietadev, I would like to request assignment to this issue. Is it possible to get it assigned?
As a Stellar ecosystem contributor, I have extensive experience in the ecosystem and would love to contribute to this project.

**Comment by earrietadev** [comment]
Closing this as this is already included in the library
