### ISSUE TITLE
NextJS / Webpack compilation error

### ISSUE THREAD

**Issue by mootz12** [Creit-Tech/Stellar-Wallets-Kit#15]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

There is a compilation error when using this package with a NextJS 12 version project.

Versions:
```json
    "@creit.tech/stellar-wallets-kit": "^0.5.0",
    "next": "^12.3.4",
    "react": "^18.2.0",
    "stellar-sdk": "^11.2.0",
```

Error:
```
> next build

info  - Linting and checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

static/chunks/pages/_app-322ca9d28969cb07.js from Terser
Unexpected token: punc ({) [static/chunks/pages/_app-322ca9d28969cb07.js:17163,11]
    at js_error (/Users/mootz12/dev/blend/blend-ui/node_modules/next/dist/compiled/terser/bundle.min.js:1:32780)
```

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

This can be fixed by upgrading to NextJS 14, so it is possible this issue is out of scope for your library.

If so, feel free to comment as such and close.

**Comment by earrietadev** [comment]
Hi @mootz12, even doe we found out last month that using `import {...} from '@creit.tech/stellar-wallets-kit/build/main' was a workaround for your case... I updated the building method with the latest version, when you have a moment could you upgrade and let me know if with this new version you're able to import it normally?

Thanks in advance!

**Comment by earrietadev** [comment]
Closing this, if it still happens with newer versions of the kit we can re-open this
