### ISSUE TITLE
Rabet wallet signing transaction invalid XDR

### ISSUE THREAD

**Issue by OleksiiN-DevBrother** [Creit-Tech/Stellar-Wallets-Kit#17]
- **I'm submitting a ...**
  [x] bug report

- Rabet wallet signing transaction doesn't work

- All other wallets work good, only Rabet returns the error 'Invalid XDR'
Code example:
 `import { TransactionBuilder } from 'stellar-sdk'`;
 
 `let transaction = new TransactionBuilder(account, {
    fee,
    networkPassphrase: Networks.TESTNET,
  })
    .addOperation(contract.call(func_name, ...args))
    .setTimeout(30)
    .build();`
    
   ` const { result } = await stellarWalletsKit.signTx({
      xdr: transaction.toXDR(),
      publicKeys: [user_address],
      network: Networks.TESTNET,
    });
 `
 
<img width="385" alt="image" src="https://github.com/Creit-Tech/Stellar-Wallets-Kit/assets/111960345/6e000a67-253d-4b97-9971-1da91750b197">

All other wallets works fine.

Or may be I'm doing it wrong?

**Comment by earrietadev** [comment]
No problem, closing this issue. You can open another one if you face any issue
