### ISSUE TITLE
Allow devs to disable the colors by light/dark mode and instead let them decide which colors to use

### ISSUE THREAD

**Issue by earrietadev** [Creit-Tech/Stellar-Wallets-Kit#20]

**Comment by No-bodyq** [comment]
Is this open for contribution??

**Comment by Vaibhav0-1** [comment]
I'm ready to take up this issue, Please assign it to me @earrietadev

**Comment by martinvibes** [comment]
@earrietadev  i would like to contribute to this

**Comment by nemealfaro** [comment]
Hi @earrietadev I would like to take this task. This would be my firts issue on this project.
I estimate no more than a 3 days  for the changes to be ready.

**Comment by No-bodyq** [comment]
Hello, Can I get assigned to this??

**Comment by Josh-121** [comment]
Can I be assigned this?

**Comment by GreatJeremy** [comment]
I would love to contribute to this project.

**Comment by od-hunter** [comment]
Thank you 🙏🏾

**Comment by earrietadev** [comment]
> Is this open for contribution? If yes, please I'll love to be assigned this issue please. This is my first time contributing to Stellar and I will love to be given the opportunity to proof my skills. To solve this issue I will:
> 
> 1. Introduce a configuration option to disable light/dark mode colors.
> 2. Allow developers to specify custom colors.
> 3. Use TypeScript interfaces to ensure type safety.
> 4. Update color handling logic to apply custom colors when configured.
> 
> I’ll submit a PR within 3-5 working days once I’m assigned.
> 
> Here is my Onlydust profile link https://app.onlydust.com/u/od-hunter , it might not look like it yet because I’m new to Onlydust, please give me the opportunity.

@od-hunter I just assigned this to you, you can ask question here. For the implementation keep in mind that the configuration needs to be "dead simple" so any the configuration needs to be at the creation level, something like this:
```ts
const kit: StellarWalletsKit = new StellarWalletsKit({
  network: WalletNetwork.TESTNET,
  selectedWalletId: XBULL_ID,
  modules: allowAllModules(),
  styles: {
    ...configuration_here
  }
})
```

Since is not going to change with the system mode, you also need to allow developers to update the color after it was created so it needs to have something like a function `kit.updateStyles({ ...configuration_here })`

**Comment by ktarun1419** [comment]
Hi i want to work on this issue @earrietadev

**Comment by od-hunter** [comment]
> Hi i want to work on this issue @earrietadev

Sorry I’m working on it already. I’ll send my PR soon🙏🏾

**Comment by od-hunter** [comment]
@earrietadev please review

**Comment by martinvibes** [comment]
hello @earrietadev sorry .I have been busy lately but now I'm free.
so I have been having issues lately with the opening/starting the live server and can you please enlighten me more on the issue

**Comment by od-hunter** [comment]
hello @earrietadev sorry .I have been busy lately but now I'm free.
so I have been having issues lately with the opening/starting the live server and can you please enlighten me more on the issue

**Comment by od-hunter** [comment]
Hello @earrietadev I’m still yet to hear from you

**Comment by earrietadev** [comment]
@od-hunter I answered you a week ago: https://github.com/Creit-Tech/Stellar-Wallets-Kit/pull/23#issuecomment-2187825002

**Comment by od-hunter** [comment]
Hello @earrietadev sorry I didn’t know, can you please describe how I'm supposed to start the live server because it's not described in the package.json file. So sorry for the delay.

**Comment by ikemHood** [comment]
Hi @earrietadev  I want to work on this issue

**Comment by od-hunter** [comment]
Hello @earrietadev please I’d not be able to continue this issue, kindly assign to someone else🙏🏾
Sorry for the inconveniences caused.

**Comment by ikemHood** [comment]
Hey @earrietadev Can I take on this now?

**Comment by earrietadev** [comment]
Hi @ikemHood, thanks but I'm already doing it myself

**Comment by ikemHood** [comment]
Too bad. i had already implemented it.

**Comment by earrietadev** [comment]
@ikemHood you're always free to submit your pull request if you want

**Comment by earrietadev** [comment]
Merged at https://github.com/Creit-Tech/Stellar-Wallets-Kit/pull/33
