### ISSUE TITLE
There might be a problem with the dependency declaration for @creit-tech/xbull-wallet-connect

### ISSUE THREAD

**Issue by jeesunikim** [Creit-Tech/Stellar-Wallets-Kit#21]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
when I ran `npm ls tslib` locally, I saw the following error `invalid: "github:Creit-Tech/xBull-Wallet-Connect#0.2.0" from node_modules/@creit.tech/stellar-wallets-kit` which is odd because it seems to be [a valid github url](https://github.com/Creit-Tech/xBull-Wallet-Connect) with the correct release. But I figured I should let you know

<img width="1055" alt="invalid" src="https://github.com/Creit-Tech/Stellar-Wallets-Kit/assets/3912060/f08fc1b3-a608-46c3-97bc-bfab221065d5">

**Comment by earrietadev** [comment]
Yeah this is common because not all tools recognize importing libraries from public github repos. Something I plan to do is deploying the xbull connect library to npm so these types of errors don't happen, probably will work on that today or tomorrow. I'll let you know once is updated

**Comment by earrietadev** [comment]
Sorry for the big delay on this, the latest version of the kit fixes this because now the xbull-wallet-connect package is loaded from npm instead of github.
