### ISSUE TITLE
Order rank wallets based on recently used or plugins available in the browsers

### ISSUE THREAD

**Issue by janewang** [Creit-Tech/Stellar-Wallets-Kit#28]
### Optimization on Wallet Ordering
The list of wallets shown to the user is defined by the developer during setup. The wallet selector could do a few things to improve the end user experience.

The first thing is that the library could detect any browser wallets and display those at the top under the wallet section, as the user is already using those wallet. 

The second thing is that if a user has used a specific wallet in the past, the selector shows this wallet at the top. 

The order of the wallets should be:

- Wallet last used by wallet selector
- If not wallet last use, wallets detected in the browser
- Wallet ordering as defined by the developer

**Comment by earrietadev** [comment]
This is now included in the new version of the kit https://github.com/Creit-Tech/Stellar-Wallets-Kit/releases/tag/v0.9.1
