### ISSUE TITLE
Update Getting Started Kit on the Official Dev Docs to use the Stellar wallets kit

### ISSUE THREAD

**Issue by janewang** [Creit-Tech/Stellar-Wallets-Kit#29]
Add to  [Getting started guide](https://soroban.stellar.org/docs/getting-started/create-an-app) here to use the wallet selector kit: https://github.com/Creit-Tech/Stellar-Wallets-Kit

Related: https://github.com/stellar/stellar-docs/issues/443

**Comment by Gift-Naomi** [comment]
@janewang Is this issue open for contributions?
If yes, can I work on it?

**Comment by briwylde08** [comment]
Hello, if you're interested in working on this, please head over to this issue in the docs: https://github.com/stellar/stellar-docs/issues/766

Comment there and I will assign the issue to you!

**Comment by Gift-Naomi** [comment]
> Hello, if you're interested in working on this, please head over to this issue in the docs: [stellar/stellar-docs#766](https://github.com/stellar/stellar-docs/issues/766)
> 
> Comment there and I will assign the issue to you!

I just did

**Comment by janewang** [comment]
Thank you, closing this issue on this repo. Please refer to the issue Bri created. Thanks!
