### ISSUE TITLE
Stellar Wallet Kit should offer a dropdown UI once wallet is connected

### ISSUE THREAD

**Issue by janewang** [Creit-Tech/Stellar-Wallets-Kit#34]
**I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project
  
  
**Summary**
Similar to Rainbow kit that has a UI once a wallet is connected, the UI shows 
- address
- native XLM balance 
- Copy address button
- Disconnect button

Before as we are implementing wallet kit on stellar lab, we realized this need: 
<img width="865" alt="Screenshot 2024-08-14 at 2 35 50 PM" src="https://github.com/user-attachments/assets/2a1f7472-082b-4a7f-b53c-310782ca8bef">

**Comment by raizo07** [comment]
@janewang is this open for contributions?

**Comment by earrietadev** [comment]
A built-in button component with a dropdown is now included in the latest version [v1.1.0](https://github.com/Creit-Tech/Stellar-Wallets-Kit/releases/tag/v1.1.0)
