### ISSUE TITLE
No way to update network after establishing wallet connection

### ISSUE THREAD

**Issue by mihaic195** [Creit-Tech/Stellar-Wallets-Kit#36]
There is no way to update the network (PUBLIC/TESTNET) after initial wallet connection. I should be able to listen to wallet changes and adjust the selected network accordingly, without re-establishing a new connection.

**Comment by earrietadev** [comment]
@mihaic195 listening to network changes is not part of the [SEP-0043](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0043.md) standard which is what this kit follows, you can still define the network to use when asking for signing but be aware that not all wallets handle this or not all of them support all the networks.

**Comment by mihaic195** [comment]
@earrietadev Thanks for the answer, this helped understand what I need!
