### ISSUE TITLE
Disconnect-button does not correctly disconnect the wallet

### ISSUE THREAD

**Issue by kovipu** [Creit-Tech/Stellar-Wallets-Kit#38]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Disconnecting a wallet using the button included in the library, does not correctly clear the browser storage. After a refresh, `kit.getAddress()` still returns the old address and the old wallet is still connected.

This appears to only happen when calling the `kit.getAddress()` function. Is this how it's intended to work? Should I be checking the connection state before calling `getAddress`?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I am using the library in my React + Soroban app. The connector code between React & Stellar Wallets Kit is not the most perfect implementation. [Relevant code.](https://github.com/Laina-Protocol/Laina/blob/main/src/stellar-wallet.tsx)

**Comment by earrietadev** [comment]
Hi @kovipu, the button removes the address from the component itself and the kit, but if you execute `kit.getAddress()` and the wallet already accepts requests from a website it will return the current address from the selected wallet (this is how stellar wallets work).

On the logic of your website you should keep track if the user was disconnected or not using the button. When creating a button, the function accepts a parameter called `onDisconnect` which is executed after the user has disconnected itself from the button component.

**Comment by kovipu** [comment]
Alright, that makes sense then. I will add the connected state to our dApp.

Thank you 🙇
