### ISSUE TITLE
Modal Popup Position Error

### ISSUE THREAD

**Issue by jeesunikim** [Creit-Tech/Stellar-Wallets-Kit#40]
- **I'm submitting a ...**
- [x] bug report
- [ ] feature 
- [ ] question about the decisions made in the repository
- [ ] question about how to use this project

- **Summary**
![stellar-wallets-kit-bug](https://github.com/user-attachments/assets/0594dbab-fbc7-46b6-88ca-fb49a7214a3a)
- When user is logged out and try to log in via the kit on mobile, its modal's position is off

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by earrietadev** [comment]
@jeesunikim is there a public preview with that one? I need to see how the kit is attaching the modal to the DOM in order to be able to fix it

**Comment by jeesunikim** [comment]
@earrietadev here you go http://laboratory-pr1080.previews.kube001.services.stellar-ops.com/

**Comment by earrietadev** [comment]
@jeesunikim the new version v1.2.3 should fix this issue, let me know if is ok now

**Comment by jeesunikim** [comment]
works great. thanks
