### ISSUE TITLE
Getting "Error: Wallet id "hana" is not supported"

### ISSUE THREAD

**Issue by FidelVe** [Creit-Tech/Stellar-Wallets-Kit#43]
There seems to be a bug when trying to instantiate the kit with Hana directly

For example, doing this will throw the error in the issue title (`Wallet id "hana" is not supported`)
```
const kit: StellarWalletsKit = new StellarWalletsKit({
         network: WalletNetwork.PUBLIC,
         modules: [HanaModule],
         selectedWalletId: HANA_ID,
       });
  ```
I could make it work by using `allowAllModules` and selecting another wallet ID then triggering the Modal and then selecting Hana as the wallet but this is not the user flow I need to design.

I need to avoid the modal from the kit to select the wallet and go directly with hana.

**Comment by earrietadev** [comment]
@FidelVe when adding the modules, you need to pass `modules: [new HanaModule()]` because is a class that needs to be instantiated.

**Comment by FidelVe** [comment]
you are correct, thank for the reply
