### ISSUE TITLE
Rabet Error: "ReferenceError: window is not defined" on testing

### ISSUE THREAD

**Issue by jeesunikim** [Creit-Tech/Stellar-Wallets-Kit#44]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

[Stellar Lab](https://lab.stellar.org/) had to remove Rabet from the wallets kit. We kept getting the `ReferenceError: window is not defined` error when Rabet was enabled.

![image](https://github.com/user-attachments/assets/76674ee9-52e1-490f-82ad-be7121380647)

**Comment by earrietadev** [comment]
Hi @jeesunikim I deployed a new version where it checks if the `window` object is available before it tries to use it in both Hana and Rabet wallets.

Let me know if this fixes the issue
