### ISSUE TITLE
signMessage for freighter wallet returns wrong values 

### ISSUE THREAD

**Issue by FidelVe** [Creit-Tech/Stellar-Wallets-Kit#45]
Good day team.

Calling `signMessage` method with freighter wallet returns `[object Object]` as the value for `signedMessage` key in the response object.
![image](https://github.com/user-attachments/assets/d38e983f-df4f-42de-9d64-5d6b32110084)

**Comment by earrietadev** [comment]
Hi there, thanks for the heads up. It looks like the `Buffer` returned from the Freighter CLI is not a NodeJS Buffer like noted in the types (I also created a [ticket](https://github.com/stellar/freighter/issues/1626) on their repo to ask for that).

I deployed a new version of the kit that handles this and you should get the correct string value

**Comment by FidelVe** [comment]
thanks, it works now
