### ISSUE TITLE
Lobstr app does not connect on mobile

### ISSUE THREAD

**Issue by kstulgys** [Creit-Tech/Stellar-Wallets-Kit#50]
I have integrated the kit on a website. Wallet connects fine on desktop, but if I click on lobstr on mobile in mobile (chrome) browser it does not do anything. I would expect it would bring my lobstr app on my phone and ask to connect. Is this is expected that lobstr does not connect on mobile?

**Comment by Lisa238-Dev** [comment]
> I have integrated the kit on a website. Wallet connects fine on desktop, but if I click on lobstr on mobile in mobile (chrome) browser it does not do anything. I would expect it would bring my lobstr app on my phone and ask to connect. Is this is expected that lobstr does not connect on mobile?



Hello @kstulgys 
You’re experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID KIT17638
Please see the link below to our dedicated support line:
[Stellar Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by earrietadev** [comment]
@kstulgys the Lobstr option is for the browser extension they made, is not for their mobile app. If you want to connect Lobstr on mobile you need to use WalletConnect instead and search for the app directly from the list of wallets WalletConnect supports.

**Comment by kstulgys** [comment]
@earrietadev thats, what I thought, thank you for the answer. Do you know, does all wallets that stellarwalletskit support supports walletconnect?

**Comment by earrietadev** [comment]
@kstulgys there are only two wallets that support WalletConnect: xBull and Lobstr.

Closing this as this issue because is not a problem with the kit
