### ISSUE TITLE
Make walletconnect optional

### ISSUE THREAD

**Issue by tyvdh** [Creit-Tech/Stellar-Wallets-Kit#6]
The wallet connect dependencies are quite large and I never use them. It would be nice to make walletconnect an optional dependency to help lighten the load of this package.

**Comment by earrietadev** [comment]
That's a good idea, actually I was planning in removing it but I think making it optional is a better approach. I will include this in the next version

**Comment by earrietadev** [comment]
I have made a full refactor of the library (getting ready for future wallets thanks to Soroban) and v0.5.0 now allows to completely avoid modules we don't want to import... WalletConnect has also been removed because it got outdated, I will add it again later
